### ISSUE TITLE
"My Dojo" bug

### ISSUE THREAD

**Issue by malderete** [ninja-ide/ninja-ide-web#1]
When log-in the "My Dojo" (in chrome using the "malderete" username) the image/link is not properly showed
I post a image about it http://ubuntuone.com/5qT9s6xt1FzVO9VSkLrAWe
I think the problem is because of the long of the username

**Comment by pmourelle** [comment]
Wow, this is a really lousy feedback from my part. I apologize.
Yes, you're right, the long names breaks the design (the link you provide is no more available, still I remember the issue).
The site will have some changes that will fix this issue, among others.
