### ISSUE TITLE
wrong text in /using 

### ISSUE THREAD

**Issue by alekibango** [ninja-ide/ninja-ide-web#18]
website/ninja_web/templates/using.html contains wrong phrase which is not proper engrish.

 <p>This is so obvious that hurt. For real.</p>

I would change the text to:  "Ninjas are dogfooding"

explanation for those who do not know what dogfooding is:
- http://www.urbandictionary.com/define.php?term=dogfooding+%28to+dogfood%29
- https://en.wikipedia.org/wiki/Eating_your_own_dog_food

**Comment by pmourelle** [comment]
I take what you say about "engrish" and agree.
About the dogfooding I'm gonna use the very same phrase (corrected in this case): is so obvious that it hurts.
