### ISSUE TITLE
No functionality for updating vote for plug-ins

### ISSUE THREAD

**Issue by yatharth** [ninja-ide/ninja-ide-web#22]
Just noticed that once you vote for a plug-in, there's no way to change it. Further attempts to vote result in a message saying "You can't vote twice". Duh, you can't (and shouldn't be able to), but we should have the choice to change our vote.

Should be a simple fix. Or is this by design?

**Update:** Looking at the other issue, it seems that this functionality is by-design. So in that case, this wouldn't be a bug report but a feature request. So, could we have it?

**Comment by pmourelle** [comment]
Hi there. Indeed it was thougt like that because of the initial contest (winner was the better ranked and could have some troubles.
Summing up: It's a feature request, and we take note of it to implement in future. Thanks.
