### ISSUE TITLE
Mac download not in downloads section

### ISSUE THREAD

**Issue by davidfokkema** [ninja-ide/ninja-ide-web#6]
When using a Mac the homepage tells me there is a Mac download available. When clicking on the overlay button, it takes me to the download section, which tells me that there is _no_ Mac download available (still training). However, the github pages show a Mac download.

**Comment by pmourelle** [comment]
Hi there David. Indeed, the link isn't in the web yet. You may download the Mac package from github by now.
We are about to upload a huge update to the website that will fix that and other bugs so then will be easier for us to mantain updated all the download section.

**Comment by davidfokkema** [comment]
Great, thanks!

Op 25 feb. 2012 om 17:53 heeft Pedroreply@reply.github.com het volgende geschreven:
