### ISSUE TITLE
Permitir Actualizaciones de los Plugins

### ISSUE THREAD

**Issue by diegosarmentero** [ninja-ide/ninja-ide-web#7]
Actualmente esta soportado poder cargar plugin con el numero de version, pero el autor de dicho plugin deberia poseer una opción de poder cargar una nueva version, donde el formulario serio uno mas reducido al de cargar plugin, conteniendo los campos:
- Descripcion
- Version
- Archivo

Por el momento se decidio no guardar los distintos arcihvos de versiones, por lo que al subir una nueva version, se pisan estos 3 campos en lo que ya se encontraba subido.

**Comment by matiasherranz** [comment]
Done in commits 99d4c4c, de194ca, 68c5930 and 8fa97e6.
