### ISSUE TITLE
Poder cargar Plugins Oficiales

### ISSUE THREAD

**Issue by diegosarmentero** [ninja-ide/ninja-ide-web#8]
Actualmente no se pueden cargar plugins "oficiales" (es decir: creados por los desarrolladores de ninja) desde la pagina, y el mantenimiento de los plugins que hacemos nosotros mismos es un tanto complejo y genera problemas.
Deberia poder cargarse plugins, y que si el usuario que los carga es uno de los marcados como "desarrolladores" (o algo), ese plugin se suba como oficial.

Deberia haber un tipo de busqueda en la sección plugins, para poder filtrar por plugins: oficiales y de la comunidad.

**Comment by matiasherranz** [comment]
Listo!

Se pueden cargar desde el admin de django, al cuál sólo tenemos acceso los miembros del staff. Cuando un plugin es cargado por esta vía, aparece en el json devuelto por esta url: <hostname>/plugins/official/

**Comment by pmourelle** [comment]
Ahora el acceso a los json de info son con una 'api' de por medio, literalmente:
plugins/api/official
plugins/api/community
plugins/api/<cadena_a_buscar_en_author_name_y_description>
plugins/api/

Además para schemes:
schemes/api/

Las URLs anteriores se mantienen por compatibilidad con ninjas "viejos". Diego hizo el update en ninja para las nuevas dires.
