### ISSUE TITLE
Cargar Schemes del Editor

### ISSUE THREAD

**Issue by diegosarmentero** [ninja-ide/ninja-ide-web#9]
El manejo de los schemes del editor para descarga, actualmente es un json hardcodeado en la pagina, lo que hace dificil el mantenimiento e incoporación de nuevos por parte de la comunidad.
Deberia haber algun formulario accesible desde la seccion plugins, donde se permitiera cargar schemes para el editor.
Los campos requeridos serian: 
- Nombre del scheme (quizas verificar que no haya ya un scheme con ese nombre?)
- Campo de texto donde ingresar el json del scheme.

**Comment by pmourelle** [comment]
Completado.
El único detalle es que el server no quiere saber nada con la app 'schemes'.
Cierro el ticket como completo, es un ticket nuevo #17 el que traba el asunto.
